name: Debug V2

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv PyGithub
        
    - name: Create Environment
      run: |
        echo "REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}" > .env
        echo "REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}" >> .env
        echo "GIT_TOKEN=${{ secrets.GIT_TOKEN }}" >> .env
        echo "Environment file created"
        
    - name: Test Environment Variables
      run: |
        python -c "
        import os
        from dotenv import load_dotenv
        load_dotenv()
        print('REDDIT_CLIENT_ID:', '✅ FOUND' if os.getenv('REDDIT_CLIENT_ID') else '❌ MISSING')
        print('REDDIT_CLIENT_SECRET:', '✅ FOUND' if os.getenv('REDDIT_CLIENT_SECRET') else '❌ MISSING')
        print('GIT_TOKEN:', '✅ FOUND' if os.getenv('GIT_TOKEN') else '❌ MISSING')
        "
        
    - name: Test Script Import
      run: |
        echo "Testing script import..."
        python -c "import misc_py_root.reddit_monitor_simple; print('✅ Script imports successfully')"
        
    - name: Test Script Execution
      run: |
        echo "Testing script execution..."
        python misc_py_root/reddit_monitor_simple.py
        
    - name: Show Results
      run: |
        echo "Checking for output files..."
        ls -la reddit_monitoring/ || echo "No reddit_monitoring directory found"
        
    - name: Success
      run: |
        echo "🎉 Debug complete!"
