name: Reddit Monitor

on:
  schedule:
    # Run every 4 hours (UTC)
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        pip install requests python-dotenv
        
    - name: Create Environment
      run: |
        echo "REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}" > .env
        echo "REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}" >> .env
        
    - name: Run Reddit Monitor
      run: |
        echo "Starting Reddit monitoring..."
        python reddit-monitor/scripts/reddit_monitor_phase1.py
        
    - name: Commit Results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reddit-monitor/data/
        git commit -m "Update Reddit monitoring data - $(date)" || echo "No changes"
        git push
        
    - name: Success
      run: |
        echo "🎉 Reddit monitoring completed successfully!"
