name: Test GitHub Actions

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Action
      run: |
        echo "✅ GitHub Actions is working!"
        echo "Current time: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
